### ISSUE TITLE
I updated the my native Installation of gamevault and Just getting a Json file as the Webinterface

### ISSUE THREAD

**Issue by Eulenhorn** [Phalcode/gamevault-backend#394]
**Describe the bug**
 I updated the my native Installation of gamevault from ~15.2 to 16.2.0 using the on the site provided commands and the server just hosts a json file with {
  "message": "ENOENT: no such file or directory, stat '/config/frontend/dist/index.html'",
  "error": "Not Found",
  "statusCode": 404
}

**Desktop (please complete the following information):**
 - OS Windows 10
 - Browser Firefox

**Comment by Eulenhorn** [comment]
I fixed it by extracting the gamevault-frontend.zip which didnt get extracted for some reason

**Comment by Alfagun74** [comment]
maybe it was an unlucky server/container restart. unfortunately the problem doesnt fix itself because it only checks for existance of that zip. But nice you found a solution!
